version: "3.9"

services:
  backend:
    container_name: link_up_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - path: ./backend/.env
        required: true

  #   depends_on:
  #     db:
  #       condition: service_healthy

  # frontend:
  #   container_name: link_up_frontend
  #   restart: always
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.frontend
  #   volumes: 
  #     - ./frontend:/frontend
  #     - /frontend/node_modules
  #   ports:
  #     - "5173:5173"
  #   env_file:
  #     - path: ./frontend/.env
  #       required: true

  #   depends_on:
  #     db:
  #       condition: service_healthy

  # db:
  #   container_name: db
  #   restart: always
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin123
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
